### ISSUE TITLE
Error caused by lack of downloadable content for an album

### ISSUE THREAD

**Issue by markHadman** [meeb/bandcampsync#4]
I'm getting stuck on this one every time. ~~I'm far from sure, but guessing it might be the '?' in the album title~~

```
2023-09-20 15:57:20,265 sync [INFO] New media item, will download: "MZYLKYPOP / Kiedy Wilki Zawyja ? "(id:4089197226) in "vorbis"
Traceback (most recent call last):
  File "/[redacted]/lib/python3.11/site-packages/bandcampsync/bandcamp.py", line 243, in get_download_file_url
    downloads = digital_item['downloads']
                ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'downloads'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/[redacted]/bin/bandcampsync", line 41, in <module>
    do_sync(cookies_path, cookies, dir_path, media_format)
  File "[redacted]/lib/python3.11/site-packages/bandcampsync/__init__.py", line 31, in do_sync
    initial_download_url = bandcamp.get_download_file_url(item, encoding=media_format)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[redacted]/lib/python3.11/site-packages/bandcampsync/bandcamp.py", line 245, in get_download_file_url
    raise BandcampError(f'Failed to parse pagedata JSON, does not contain an '
bandcampsync.bandcamp.BandcampError: Failed to parse pagedata JSON, does not contain an "digital_items.downloads" key

```

**Comment by markHadman** [comment]
You're right, it looks like they've removed the downloadable content from this album. I'll amend the issue title (and send a snotty email to the artist)

**Comment by meeb** [comment]
The above neater error log message patch will be in the next release. There's not much else I can do here to handle this. Happy to close the issue?

**Comment by markHadman** [comment]
I've tested your fix and it works for me. Closing
